### PR TITLE
installed probot stale, under recommendation of jason

### PR DESCRIPTION
**Pull request by KaiFish**
this should let us use the stale plugin. Config file will appear in the repo the probot is added to.

### CODE REVIEW

**Comment by KaiFish** [comment]
Node.js 8 and Yarn do not seem to get along

**Comment by hiimbex** [comment]
👋 greetings from the **probot team**! So excited for this project. 

Specific to this PR, we would recommend _against_ pulling in additional probot apps in this manner. The reasoning for that is that stale already has a deployed version [here](https://github.com/apps/stale/installations/new) that can already be installed to your repository. The reason for that is that you aren't making any changes to the way stale works specific to your app, so the version that works for everyone can work for you too!

The use cases for combining apps is usually when you want to only deploy multiple apps together. Take for example [welcome](https://github.com/behaviorbot/welcome). It runs on [3 individual probot apps](https://github.com/behaviorbot/welcome/blob/master/package.json), [new-issue-welcome](https://github.com/behaviorbot/new-issue-welcome), [new-pr-welcome](https://github.com/behaviorbot/new-pr-welcome), and [first-pr-merge](https://github.com/behaviorbot/first-pr-merge). None of those 3 individual apps have individual GitHub Apps associated with them, so the only way to get access to them is by installing the combined app, which makes sense given their similarities to each other.

Stale on the other hand is much more independent. However, if you still wish to host it on your own, you'll need to follow the syntax documented [here](https://probot.github.io/docs/deployment/#combining-apps) to correctly add it in your `package.json`. You'll need to add:
```
"probot": {
   "plugins": [
     "probot-stale"
   ]
 }
```
I'd also recommend depending on the stale repo, rather than the npm package, since that package is not frequently updated. (It's not frequently updated because there are very few use cases where recommend using stale in this manner as opposed to installing [our hosted version](https://github.com/apps/stale/installations/new).)

**Comment by joenash** [comment]
@hiimbex hey Bex! 

We were actually going to hit this with a brick, and just have one probot monolith probot app with all the functionality in it as scripts, rather than make use of plugins and multiple instances. Partly because we're at a hackday, partly for newbie accessibility. You can see the approach we're taking here: https://github.com/campus-experts/prefect/tree/master/src

Lemme know how criminally dumb we're being!

**Comment by hiimbex** [comment]
That sounds good to me Joe! I would definitely agree having scripts is a good plan. It's just then not possible to bring in functionality from pre-existing apps without also installing them. So if you wanna make use of stale, you can't so so in that manner. 

Let me know if you run into any blockers or have any questions. I can jump on the zoom if you need :)

**Pull request closed without merging**
